version: '3'

services:
  app:
    build: $PWD/apache2/
    volumes:
      - $PWD/apache2/php.ini:/usr/local/etc/php/php.ini
      - $PWD/apache2/conf/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - $PWD/www:/var/www
    ports:
      - 81:80 #http://localhost:81
    env_file:
      - $PWD/apache2/docker-apache2.env
    
  mysql:
    build: $PWD/mysql/
    volumes:
      - $PWD/mysql/DB:/docker-entrypoint-initdb.d
    ports:
      - "4307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    links:
      - mysql
    ports:
      - 4041:80 #http://localhost:4041
    volumes:
      - $PWD/phpmyadmin/sessions:/sessions
      