version: '3'

services:
  app:
    build: ./apache2/
    volumes:
      - ./apache2/php.ini:/usr/local/etc/php/php.ini
      - ./apache2/conf/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./www:/var/www
    ports:
      - 81:80 #http://localhost:81
    env_file:
      - ./apache2/docker-apache2.env
    depends_on:
      - db
    
  db:
    build: ./mysql/
    volumes:
      - ./mysql/DB:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    ports:
      - "4307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db
    ports:
      - 4041:80 #http://localhost:4041
    volumes:
      - ./phpmyadmin/sessions:/sessions
      